### ISSUE TITLE
different glyph names in regular and bold

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/font-tagmukay#1]
There are four glyphs that have different names in regular and bold, and two glyphs that are in a different order between regular and bold. 

I generated a list of glyphnames (in glyph order) for both fonts and diffed them with Tortoise. Here is a screenshot showing the differences (left side is bold, right side is regular):
![image](https://user-images.githubusercontent.com/6842108/27887481-3c6089fa-619e-11e7-8a34-b1112bf8c113.png)

I'm not confident of all the implications, but one is that at least those first four are not getting renamed by FFChangeGlyphNames when building the Bold font.

**Comment by jcoblentz** [comment]
Good catch Bob! Corrected glyph names in Regular-source.ttf and psnames.csv. Correcte…
…d glyph order in Bold-source.ttf.
